'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o recompile su proyecto de VS.
    '''<summary>
    '''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class langres
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("DuckEncoder.langres", GetType(langres).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Abrir.
        '''</summary>
        Friend Shared ReadOnly Property Abrir() As String
            Get
                Return ResourceManager.GetString("Abrir", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Aceptar.
        '''</summary>
        Friend Shared ReadOnly Property Aceptar() As String
            Get
                Return ResourceManager.GetString("Aceptar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Acerca de Ducky Encoder.
        '''</summary>
        Friend Shared ReadOnly Property acercaDe() As String
            Get
                Return ResourceManager.GetString("acercaDe", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Acerca de.
        '''</summary>
        Friend Shared ReadOnly Property acerdaDeTitulo() As String
            Get
                Return ResourceManager.GetString("acerdaDeTitulo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Ajustes.
        '''</summary>
        Friend Shared ReadOnly Property Ajustes() As String
            Get
                Return ResourceManager.GetString("Ajustes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Añadir recurso modificado.
        '''</summary>
        Friend Shared ReadOnly Property AnadirModificado() As String
            Get
                Return ResourceManager.GetString("AnadirModificado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Archivo.
        '''</summary>
        Friend Shared ReadOnly Property Archivo() As String
            Get
                Return ResourceManager.GetString("Archivo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Ayuda.
        '''</summary>
        Friend Shared ReadOnly Property Ayuda() As String
            Get
                Return ResourceManager.GetString("Ayuda", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Cargar fichero.
        '''</summary>
        Friend Shared ReadOnly Property cargarFichero() As String
            Get
                Return ResourceManager.GetString("cargarFichero", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Castellano.
        '''</summary>
        Friend Shared ReadOnly Property Castellano() As String
            Get
                Return ResourceManager.GetString("Castellano", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Consola.
        '''</summary>
        Friend Shared ReadOnly Property Consola() As String
            Get
                Return ResourceManager.GetString("Consola", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Todos los derechos reservados..
        '''</summary>
        Friend Shared ReadOnly Property derechosReservados() As String
            Get
                Return ResourceManager.GetString("derechosReservados", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Encode.
        '''</summary>
        Friend Shared ReadOnly Property Encode() As String
            Get
                Return ResourceManager.GetString("Encode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Explorar.
        '''</summary>
        Friend Shared ReadOnly Property Explorar() As String
            Get
                Return ResourceManager.GetString("Explorar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Fichero guardado correctamente.
        '''</summary>
        Friend Shared ReadOnly Property ficheroGuardado() As String
            Get
                Return ResourceManager.GetString("ficheroGuardado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Guardar.
        '''</summary>
        Friend Shared ReadOnly Property Guardar() As String
            Get
                Return ResourceManager.GetString("Guardar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Guardar fichero compilado.
        '''</summary>
        Friend Shared ReadOnly Property guardarCompilado() As String
            Get
                Return ResourceManager.GetString("guardarCompilado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Guardar fichero.
        '''</summary>
        Friend Shared ReadOnly Property guardarFichero() As String
            Get
                Return ResourceManager.GetString("guardarFichero", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Idioma.
        '''</summary>
        Friend Shared ReadOnly Property Idioma() As String
            Get
                Return ResourceManager.GetString("Idioma", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Idioma aplicación.
        '''</summary>
        Friend Shared ReadOnly Property idiomaAplicacion() As String
            Get
                Return ResourceManager.GetString("idiomaAplicacion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Idioma encoder.
        '''</summary>
        Friend Shared ReadOnly Property idiomaEncoder() As String
            Get
                Return ResourceManager.GetString("idiomaEncoder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Idioma Recurso.
        '''</summary>
        Friend Shared ReadOnly Property IdiomaRecurso() As String
            Get
                Return ResourceManager.GetString("IdiomaRecurso", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Ingles.
        '''</summary>
        Friend Shared ReadOnly Property Ingles() As String
            Get
                Return ResourceManager.GetString("Ingles", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Nuevo script.
        '''</summary>
        Friend Shared ReadOnly Property lblScriptName() As String
            Get
                Return ResourceManager.GetString("lblScriptName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Normal.
        '''</summary>
        Friend Shared ReadOnly Property Normal() As String
            Get
                Return ResourceManager.GetString("Normal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Nuevo.
        '''</summary>
        Friend Shared ReadOnly Property Nuevo() As String
            Get
                Return ResourceManager.GetString("Nuevo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Recurso por defecto.
        '''</summary>
        Friend Shared ReadOnly Property recursosDefecto() As String
            Get
                Return ResourceManager.GetString("recursosDefecto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Salir.
        '''</summary>
        Friend Shared ReadOnly Property Salir() As String
            Get
                Return ResourceManager.GetString("Salir", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Script no encontrado.
        '''</summary>
        Friend Shared ReadOnly Property scriptNoEncontrado() As String
            Get
                Return ResourceManager.GetString("scriptNoEncontrado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Ventana.
        '''</summary>
        Friend Shared ReadOnly Property Ventana() As String
            Get
                Return ResourceManager.GetString("Ventana", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
